gui_log_window: false
# Serenaのログを表示するグラフィカルウィンドウを開くかどうか。
# これは主にWindowsと（部分的に）Linuxでサポートされています；macOSでは利用できません。
# ログをWebブラウザで見たい場合は、代わりに`web_dashboard`オプションを使用してください。
# 制限事項：Linux版Claude Desktopのコミュニティ版では動作しないようです
# 一部のMCPクライアントでも問題を引き起こす可能性があります - 問題がある場合は、これを無効にしてみてください

# ログを検査できることは、トラブルシューティングとツール呼び出しの監視の両方に役立ちます。
# 特にagno playgroundを使用している場合、ツール呼び出しが常に表示されるとは限らず、
# 入力パラメータはagno UIで表示されることはありません。
# Claude Desktop用のMCPサーバーとして使用する場合、ログは主にトラブルシューティング用です。
# 注意：残念ながら、Serenaサーバーやエージェントを起動する様々なエンティティは
# 謎めいた方法で起動し、しばしば前のインスタンスをシャットダウンせずに
# プロセスの複数のインスタンスを起動します。これにより複数のログウィンドウが開かれ、
# 最後のウィンドウのみが更新されることになります。agnoやClaude DesktopがSerenaを
# どのように起動するかを制御できないため、今のところこの制限を受け入れる必要があります。

web_dashboard: false
# SerenaのWebダッシュボードを開くかどうか（Webブラウザからアクセス可能）。
# これはSerenaの現在のセッションログを表示し、GUIログウィンドウの代替となります。
# GUIログウィンドウは全プラットフォームでサポートされています。

web_dashboard_open_on_launch: false
# Serena起動時にWebダッシュボードでブラウザウィンドウを開くかどうか（web_dashboardが
# 有効になっている場合）。Falseに設定すると、ブラウザでhttp://localhost:24282/dashboard/
# に手動で移動することでダッシュボードを開くことができます（24282 = 0x5EDA, SErena DAshboard）。
# 複数のインスタンスが実行されている場合、より高いポートが使用されます；ポート24283、24284などを試してください。

log_level: 20
# GUIログウィンドウとダッシュボードの最小ログレベル（10 = debug、20 = info、30 = warning、40 = error）

trace_lsp_communication: false
# Serenaと言語サーバー間の通信をトレースするかどうか。
# これは言語サーバーの問題をデバッグするのに役立ちます。

tool_timeout: 240
# ツール実行が終了されるまでのタイムアウト（秒）

excluded_tools: []
# グローバルに除外するツールのリスト

included_optional_tools: []
# 含めるオプションツールのリスト（デフォルトでは無効）

jetbrains: false
# JetBrainsモードを有効にして、言語サーバーベースのツールの代わりに
# Serena JetBrains IDEプラグインに基づくツールを使用するかどうか
# 注意：プラグインはまだリリースされていません。これはSerena開発者専用です。


default_max_tool_answer_chars: 150000
# applyメソッドにデフォルトの最大回答長があるツールのデフォルトとして使用されます。
# max_answer_charsの値はツール呼び出し時に変更できますが、グローバル設定を通じて
# このデフォルトを調整することも意味があります。

record_tool_usage_stats: false
# ツール使用統計を記録するかどうか。記録がアクティブな場合、Webダッシュボードに表示されます。

token_count_estimator: TIKTOKEN_GPT4O
# `record_tool_usage`がTrueの場合のみ関連します；ツール使用統計に使用するトークン数推定器の名前。
# 利用可能なオプションについては`RegisteredTokenCountEstimator`列挙型を参照してください。
#
# 注意：一部のトークン推定器（tiktokenなど）は初回実行時にデータファイルのダウンロードが必要で、
# これには時間がかかり、インターネットアクセスが必要になる場合があります。その他、Anthropicのものなどは
# APIキーが必要で、レート制限が適用される場合があります。


# SERENAによって管理されます。YAMLの最下部に保持し、必要がない限り編集しないでください
# 登録されたプロジェクトのリスト。
# プロジェクトを追加するには、チャット内で単純にSerenaに
# "activate the project /path/to/project"または、
# プロジェクトが以前に追加されている場合は"activate the project <project name>"と
# 依頼してください。
# デフォルトでは、プロジェクトの名前はプロジェクトを含むディレクトリの名前になりますが、
# （自動生成される）プロジェクト設定ファイル`/path/project/project/.serena/project.yml`を
# 編集することで変更できます。
# プロジェクト設定を完全に制御したい場合は、project.ymlファイルを手動で作成してから、
# 初回アクティベーションのためにSerenaにパスでプロジェクトをアクティベートするよう指示してください。
# 注意：登録されたプロジェクトの名前に名前の衝突がないことを確認してください。
projects:
- /Users/wake_yuki/dev/almondo/pj_leadcreate_assessmentsystem_phase2
- /Users/wake_yuki/dev/almondo/pj_leadcreate_assessmentsystem_phase2-2
- /Users/wake_yuki/dev/almondo/pj_ttdc_system_phase5-2/app
